version: '3.4'

networks:
  diplomaspbu-dev:
    driver: bridge

services:
  collectorapi: 
    image: collectorapi:latest
    depends_on:
      - "postgres_image"
    build: 
      context: .
      dockerfile: DatasetCollector/Dockerfile
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - shared_files:/collector
    environment:
      - DB_CONNECTION_STRING=host=postgres_image;port=5432;database=matchDB;username=collectoruser;password=collectionuser

  predictor-api:
    image: predictor-api:latest
    build: 
      context: .
      dockerfile: MLModel/Dockerfile
    restart: on-failure
    ports:
      - "8080:80"
    volumes:
      - predictor_volume:/code
  postgres_image:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=collectoruser
      - POSTGRES_PASSWORD=collectionuser
      - POSTGRES_DB=matchDB

volumes:
  postgresql_volume:
  shared_files:
  predictor_volume: